apiVersion: apps/v1
kind: Deployment
metadata:
  name: vol-deployment
  namespace: lab2
spec:
  selector:
    matchLabels:
      app: vol-dir
  replicas: 1
  template:
    metadata:
      labels:
        app: vol-dir
    spec:
      containers:
      - image: centos
        name: test-container
        command: ["sleep"]
        args: ["600"]
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        - mountPath: /data
          name: test-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: test-volume
        hostPath:
          path: <paste the copied path>
