apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod-cm-secret-deployment
  namespace: lab2
spec:
  selector:
    matchLabels:
      app: mypod-cm-secret
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod-cm-secret
    spec:
      containers:
      - name: mypod
        image: centos
        command: ["sleep"]
        args: ["600"]
        volumeMounts:
        - name: my-vol
          mountPath: /data
          readOnly: true
        - name: mysecret-vol
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: my-vol
        configMap:
          name: game-demo
      - name: mysecret-vol
        secret:
          secretName: db-user-pass
