apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: lab2
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: nginx-service
    protocol: TCP
    port: 80
    targetPort: http-web-svc
